[phases.setup]
nixpkgs = ['python3', 'gcc']

[phases.install]
cmds = ['cd backend && python -m venv --copies /opt/venv && /opt/venv/bin/pip install -r requirements.txt']

[start]
cmd = 'cd backend && /opt/venv/bin/uvicorn app.main:app --host 0.0.0.0 --port $PORT'